# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [article_update]
  push:
    branches:
      - main  # å½“æ¨é€åˆ°ä¸»åˆ†æ”¯æ—¶è§¦å‘
  schedule:
    - cron: '0 0 * * *'  # æ¯å¤©åŒæ­¥ä¸€æ¬¡


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout blog repository
      - name: Checkout blog repo
        uses: actions/checkout@v2

      # Checkout articles repository as a submodule
      - name: Checkout articles repo
        uses: actions/checkout@v2
        with:
          repository: flowstone/blog-articles
          path: content/post
          token: ${{ secrets.GITHUB_TOKEN }}

       # Set Git configuration for user identity
      - name: Set Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit and push articles changes
        run: |
          git rm --cached content/post
          git submodule add https://github.com/flowstone/blog-articles content/post
          git commit -m "Sync articles from new repository"
          git push origin main

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: sync
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # ä½ çš„ç”Ÿæˆæ–‡ä»¶å¤¹
  # Build job
  push-page:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0 # <-- clone with complete history
      - name: Sync Repo to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: flowstone
          spacename: flowstone
          repository: flowstone.bitbucket.io
          password: ${{ secrets.BITBUCKET_PASSWORD }}
      - name: Sync Repo to Coding
        uses: serverlesslife-cn/sync-repo-to-coding@master
        env:
            # åœ¨ GitHub Settings->Secrets é…ç½® CODING_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
        with:
            # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ GitHub æºä»“åº“åœ°å€
            github-repo: "git@github.com:flowstone/flowstone.github.io.git"
            # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ CODING ç›®æ ‡ä»“åº“åœ°å€
            coding-repo: "git@e.coding.net:flowstone/flowstone.coding.me.git"
      - name: Sync Repo to Gitlab
        uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ secrets.USERNAME }}
          url: ${{ secrets.GITLAB_URL }}
          # Personal access token from gitlab.com 
          token: ${{ secrets.GITLAB_PAT }}

  
